const dummyLeads = [
  {
    name: "Ahmed Khan",
    mobile: "0300-1234567",
    email: "ahmed.khan@gmail.com",
    city: "Lahore",
    service: "Web Development",
    budget: 50000,
    status: "New",
  },
  {
    name: "Sara Ali",
    mobile: "0311-2345678",
    email: "sara.ali@gmail.com",
    city: "Karachi",
    service: "Mobile App",
    budget: 80000,
    status: "Interested",
  },
  {
    name: "Usman Tariq",
    mobile: "0321-3456789",
    email: "usman.tariq@gmail.com",
    city: "Islamabad",
    service: "SEO",
    budget: 25000,
    status: "Converted",
  },
  {
    name: "Ayesha Raza",
    mobile: "0333-4567890",
    email: "ayesha.raza@gmail.com",
    city: "Lahore",
    service: "Graphic Design",
    budget: 15000,
    status: "Rejected",
  },
  {
    name: "Bilal Mahmood",
    mobile: "0345-5678901",
    email: "bilal.mahmood@gmail.com",
    city: "Faisalabad",
    service: "Web Development",
    budget: 60000,
    status: "Interested",
  },
  {
    name: "Fatima Sheikh",
    mobile: "0301-6789012",
    email: "fatima.sheikh@gmail.com",
    city: "Karachi",
    service: "Digital Marketing",
    budget: 35000,
    status: "New",
  },
  {
    name: "Hassan Nawaz",
    mobile: "0312-7890123",
    email: "hassan.nawaz@gmail.com",
    city: "Multan",
    service: "Mobile App",
    budget: 90000,
    status: "Converted",
  },
  {
    name: "Zainab Malik",
    mobile: "0322-8901234",
    email: "zainab.malik@gmail.com",
    city: "Islamabad",
    service: "SEO",
    budget: 20000,
    status: "New",
  },
  {
    name: "Omar Farooq",
    mobile: "0334-9012345",
    email: "omar.farooq@gmail.com",
    city: "Peshawar",
    service: "Graphic Design",
    budget: 18000,
    status: "Interested",
  },
  {
    name: "Hina Javed",
    mobile: "0346-0123456",
    email: "hina.javed@gmail.com",
    city: "Lahore",
    service: "Digital Marketing",
    budget: 45000,
    status: "Rejected",
  },
];

module.exports = dummyLeads;
